name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 18, 20 ]

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - run: npm ci

    - run: npm run build

    - name: npm pack
      run: |
        mkdir dist
        npm pack --pack-desination dist

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: qrcode
          path: dist/*.tgz
          compression-level: 0
