name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 18, 20, 22 ]
      fail-fast: false

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: install canvas dependencies
      run: |
        sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

    - run: npm ci

    - run: npm run build

    - name: npm pack
      run: npm pack

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: qrcode_node_${{ matrix.node }}
          path: '*.tgz'
          compression-level: 0
